name: Build & Publish Rust Wrapper Image

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          # Ajusta estas rutas según dónde esté tu Dockerfile
          context: ./games/rust
          file:    ./games/rust/Dockerfile
          push:    true
          tags:    ghcr.io/buzgero/pterodactyl-rust:custom
