name: Build & Publish Rust Wrapper Image

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          # Apunta al contexto que contiene Dockerfile, wrapper.js, entrypoint.sh, etc.
          context: ./games/rust
          # Ruta relativa al Dockerfile dentro de tu repo
          file: ./games/rust/Dockerfile
          push: true
          # Asegúrate de que tu usuario está en minúsculas
          tags: ghcr.io/buzgero/pterodactyl-rust:custom

